### ISSUE TITLE
Gradle Integration

### ISSUE THREAD

**Issue by iris410** [iris410/Reminder#2]
Goal
- Build a jar with Gradle

Acceptance Criteria
- Add `gradlew` as your build tool (reference to your pawn project)
- Add `build.gradle` file in your project
- `./gradlew build` command can build a jar of your app

**Comment by ChengGit** [comment]
## How to create a new Gradle project of `maven archetype` with Intellij?
1. create a new gradle project via Intellij
<img width="798" alt="Screenshot 2022-05-31 at 18 52 30" src="https://user-images.githubusercontent.com/7797945/171252817-ce311b59-fa6b-4d71-99aa-7098f376b2f8.png">

2. You should be able to see `src` folder and `main` and `test` sub folders are generated automatically for you.
<img width="625" alt="Screenshot 2022-05-31 at 18 58 13" src="https://user-images.githubusercontent.com/7797945/171253872-0218011d-908c-4d87-b8d0-ff1c675a66df.png">

3. Put your Main function under path `src/main/java/github/iris0410/reminder/` . It means you will need to create new folders under `main`
<img width="687" alt="Screenshot 2022-05-31 at 19 04 04" src="https://user-images.githubusercontent.com/7797945/171254900-e4d8458f-25c8-41ac-abd1-48762013492b.png">

**Comment by iris410** [comment]
done
